name:                pantomime
version:             0.1.0.0
github:              "anonymous/pantomime"
license:             BSD-3-Clause
author:              "anonymous"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/anonymous/pantomime#readme>

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveDataTypeable
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- GADTs
- ImportQualifiedPost
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeAbstractions
- TypeApplications
- TypeFamilies
- TypeOperators

dependencies:
- base >= 4.7 && < 5
- ghc >= 9.6.4
- ghc-prim
- composition
- containers
- unordered-containers
- constraints >= 0.14.2
- transformers
- template-haskell
- mtl
- microlens
- grisette >= 0.13.0.0
# TODO: Remove clash dependency once we can externalise its interpretation.
- clash-prelude
- effectful-core >= 2.5.1.0
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wprepositive-qualified-module

library:
  source-dirs: src

executables:
  pantomime-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin Pantomime
    - -fexpose-all-unfoldings
    dependencies:
    - QuickCheck
    - pantomime

tests:
  pantomime-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pantomime
    - hspec
    - HUnit
    - ghc-paths
    - directory
    - silently
