module Effectful.Grisette.Solver
  ( Solver (..)
  , SolverResult (..)
  , SolverError (..)
  , solve
  , runSolver
  ) where

import Effectful
import Effectful.Error.Static
import Effectful.Dispatch.Dynamic
import Effectful.Exception (ErrorCall (..), bracket, throwIO)

import Grisette (SymBool, ConfigurableSolver (..), solverTerminate, solverSolve, SolvingFailure (..), Model)

import Data.Text

-- | Allows access to an SMT solver to check satisfiability.
data Solver :: Effect where
  -- TODO: I guess we could make this work for non-symbolic values? Of course,
  -- the solution is trivial there and doesn't require the solver.
  Solve :: SymBool -> Solver m SolverResult

type instance DispatchOf Solver = Dynamic

-- | Check satisfiability of the given formula.
solve :: Solver :> es => SymBool -> Eff es SolverResult
solve = send . Solve

-- | Result of checking satisfiability using an SMT solver.
data SolverResult where
  Satisfiable :: Model -> SolverResult
  Unsatisfiable :: SolverResult
  Unknown :: SolverResult

-- | Error as generated by the underlying solver.
data SolverError where
  SolverError :: Text -> SolverError
  deriving Show

-- | Run an SMT 'Solver' effect that can solver 'Grisette' symbolic values.
--
-- WARNING: This effect will create a new process. If this is run at the root
-- of a program, an SMT solver instance will be active for its entire duration.
-- Instead, prefer using the 'Provider' effect to only create this process in
-- the scope where an SMT solver is actually used.
runSolver
  :: HasCallStack
  => IOE :> es
  => Error SolverError :> es
  => ConfigurableSolver config handle
  => config
  -> Eff (Solver : es) a
  -> Eff es a
runSolver cfg eff = bracket
  (liftIO $ newSolver cfg)
  (liftIO . solverTerminate)
  (\handle -> interpretWith_ eff \(Solve formula) -> do
    result <- liftIO $ solverSolve handle formula
    case result of
      Right model -> pure $ Satisfiable model
      Left Unsat -> pure Unsatisfiable
      Left Unk -> pure Unknown
      Left (SolvingError message) -> throwError $ SolverError message
      -- The following cases should be unreachable:
      Left ResultNumLimitReached -> do
        throwIO $ ErrorCall "single solver call cannot reach a result limit"
      Left Terminated -> do
        throwIO $ ErrorCall "solver cannot be terminated inside of bracket")
